import type { PopularArtist } from './types';

export const COUNTRY_CLASSIC_ARTISTS: PopularArtist[] = [
  { name: 'Johnny Cash', genre: 'Country' },
  { name: 'Dolly Parton', genre: 'Country' },
  { name: 'Willie Nelson', genre: 'Country' },
  { name: 'Luke Combs', genre: 'Country' },
  { name: 'Morgan Wallen', genre: 'Country' },
  { name: 'Kacey Musgraves', genre: 'Country' },
  { name: 'Chris Stapleton', genre: 'Country' },
  { name: 'Zach Bryan', genre: 'Country' },
  { name: 'Tyler Childers', genre: 'Country' },
  { name: 'Sturgill Simpson', genre: 'Country' },
  { name: 'Jason Isbell', genre: 'Country' },
  { name: 'Brandi Carlile', genre: 'Country / Folk' },
  { name: 'Miranda Lambert', genre: 'Country' },
  { name: 'Carrie Underwood', genre: 'Country' },
  { name: 'Keith Urban', genre: 'Country' },
  { name: 'Blake Shelton', genre: 'Country' },
  { name: 'Tim McGraw', genre: 'Country' },
  { name: 'Faith Hill', genre: 'Country' },
  { name: 'Garth Brooks', genre: 'Country' },
  { name: 'Shania Twain', genre: 'Country' },
  { name: 'Patsy Cline', genre: 'Country' },
  { name: 'Hank Williams', genre: 'Country' },
  { name: 'Merle Haggard', genre: 'Country' },
  { name: 'Waylon Jennings', genre: 'Country' },
  { name: 'Kris Kristofferson', genre: 'Country' },
  { name: 'Emmylou Harris', genre: 'Country' },
  { name: 'Loretta Lynn', genre: 'Country' },
  { name: 'Tammy Wynette', genre: 'Country' },
  { name: 'George Strait', genre: 'Country' },
  { name: 'Alan Jackson', genre: 'Country' },
  { name: 'Randy Travis', genre: 'Country' },
  { name: 'Vince Gill', genre: 'Country' },
  { name: 'Alison Krauss', genre: 'Bluegrass' },
  { name: 'Billy Strings', genre: 'Bluegrass' },
  { name: 'Mumford & Sons', genre: 'Folk' },
  { name: 'The Lumineers', genre: 'Folk' },
  { name: 'Lord Huron', genre: 'Folk' },
  { name: 'Hozier', genre: 'Folk / Soul' },
  { name: 'Leonard Cohen', genre: 'Folk' },
  { name: 'Joni Mitchell', genre: 'Folk' },
  { name: 'Simon & Garfunkel', genre: 'Folk' },
  { name: 'Crosby, Stills & Nash', genre: 'Folk rock' },
  { name: 'The Band', genre: 'Folk rock' },
  { name: 'Neil Diamond', genre: 'Pop' },
  { name: 'Enya', genre: 'New age' },
  { name: 'Yanni', genre: 'New age' },
  { name: 'Ludovico Einaudi', genre: 'Classique' },
  { name: 'Max Richter', genre: 'Classique' },
  { name: 'Ólafur Arnalds', genre: 'Classique' },
  { name: 'Nils Frahm', genre: 'Classique / Électro' },
  { name: 'Debussy', genre: 'Classique' },
  { name: 'Mozart', genre: 'Classique' },
  { name: 'Beethoven', genre: 'Classique' },
  { name: 'Bach', genre: 'Classique' },
  { name: 'Vivaldi', genre: 'Classique' },
  { name: 'Chopin', genre: 'Classique' },
  { name: 'Tchaikovsky', genre: 'Classique' },
  { name: 'Rachmaninoff', genre: 'Classique' },
  { name: 'Philip Glass', genre: 'Classique' },
  { name: 'Steve Reich', genre: 'Classique' },
  { name: 'John Williams', genre: 'Classique / Film' },
  { name: 'Hans Zimmer', genre: 'Classique / Film' },
  { name: 'Ennio Morricone', genre: 'Classique / Film' },
  { name: 'Danny Elfman', genre: 'Classique / Film' },
  { name: 'Trent Reznor', genre: 'Électro / Film' },
  { name: 'Atticus Ross', genre: 'Électro / Film' },
];
