import type { PopularArtist } from './types';

export const FR_POP_CHANSON_ARTISTS: PopularArtist[] = [
  { name: 'Stromae', genre: 'Pop / Électro FR' },
  { name: 'Angèle', genre: 'Pop FR' },
  { name: 'Christine and the Queens', genre: 'Pop / Électro FR' },
  { name: 'Vianney', genre: 'Pop FR' },
  { name: 'Zaz', genre: 'Chanson FR' },
  { name: 'Aya Nakamura', genre: 'Pop FR' },
  { name: 'Vitaa', genre: 'Pop FR' },
  { name: 'Louane', genre: 'Pop FR' },
  { name: 'Amir', genre: 'Pop FR' },
  { name: 'Indila', genre: 'Pop FR' },
  { name: 'M Pokora', genre: 'Pop FR' },
  { name: 'Kendji Girac', genre: 'Pop FR' },
  { name: 'Jenifer', genre: 'Pop FR' },
  { name: 'Santa', genre: 'Pop FR' },
  { name: 'Tayc', genre: 'Pop FR' },
  { name: 'Maureen', genre: 'Pop FR' },
  { name: 'Lous and the Yakuza', genre: 'Pop FR' },
  { name: 'Clara Luciani', genre: 'Pop FR' },
  { name: 'Pomme', genre: 'Chanson FR' },
  { name: 'Jeanne Added', genre: 'Pop FR' },
  { name: 'Yseult', genre: 'Pop FR' },
  { name: 'Hoshi', genre: 'Pop FR' },
  { name: 'Juliette Armanet', genre: 'Pop FR' },
  { name: 'Calogero', genre: 'Pop FR' },
  { name: 'Mylène Farmer', genre: 'Pop FR' },
  { name: 'Jean-Jacques Goldman', genre: 'Chanson FR' },
  { name: 'Renaud', genre: 'Chanson FR' },
  { name: 'Jacques Brel', genre: 'Chanson FR' },
  { name: 'Édith Piaf', genre: 'Chanson FR' },
  { name: 'Serge Gainsbourg', genre: 'Chanson FR' },
  { name: 'France Gall', genre: 'Chanson FR' },
  { name: 'Joe Dassin', genre: 'Chanson FR' },
  { name: 'Charles Aznavour', genre: 'Chanson FR' },
  { name: 'Florent Pagny', genre: 'Chanson FR' },
  { name: 'Patrick Bruel', genre: 'Chanson FR' },
  { name: 'Johnny Hallyday', genre: 'Rock FR' },
  { name: 'Nolwenn Leroy', genre: 'Chanson FR' },
  { name: "Keen'V", genre: 'Pop FR' },
  { name: 'Slimane', genre: 'Pop FR' },
  { name: 'Shy\'m', genre: 'Pop FR' },
  { name: 'Tal', genre: 'Pop FR' },
  { name: 'Christophe Maé', genre: 'Pop FR' },
  { name: 'Grégoire', genre: 'Pop FR' },
  { name: 'Benjamin Biolay', genre: 'Chanson FR' },
  { name: 'Camille', genre: 'Chanson FR' },
  { name: 'Barbara', genre: 'Chanson FR' },
  { name: 'Georges Brassens', genre: 'Chanson FR' },
  { name: 'Léo Ferré', genre: 'Chanson FR' },
  { name: 'Michel Polnareff', genre: 'Chanson FR' },
  { name: 'Michel Sardou', genre: 'Chanson FR' },
  { name: 'Dalida', genre: 'Chanson FR' },
  { name: 'Françoise Hardy', genre: 'Chanson FR' },
  { name: 'Vanessa Paradis', genre: 'Pop FR' },
  { name: '-M-', genre: 'Pop FR' },
  { name: 'Matmatah', genre: 'Rock FR' },
  { name: 'Noir Désir', genre: 'Rock FR' },
  { name: 'Téléphone', genre: 'Rock FR' },
  { name: 'Trust', genre: 'Rock FR' },
  { name: 'Indochine', genre: 'Rock FR' },
  { name: 'Louise Attaque', genre: 'Rock FR' },
  { name: 'Les Innocents', genre: 'Rock FR' },
  { name: 'Les Rita Mitsouko', genre: 'Rock FR' },
  { name: 'Superbus', genre: 'Rock FR' },
  { name: 'BB Brunes', genre: 'Rock FR' },
  { name: 'Feu! Chatterton', genre: 'Rock FR' },
  { name: 'L\'Impératrice', genre: 'Disco FR' },
  { name: 'Paradis', genre: 'Électro FR' },
  { name: 'SebastiAn', genre: 'Électro FR' },
  { name: 'Yuksek', genre: 'Électro FR' },
  { name: 'Cassius', genre: 'Électro FR' },
  { name: 'Air', genre: 'Électro FR' },
  { name: 'Kavinsky', genre: 'Électro FR' },
  { name: 'The Avener', genre: 'Électro FR' },
  { name: 'Petit Biscuit', genre: 'Électro FR' },
  { name: 'Madeon', genre: 'Électro FR' },
  { name: 'Woodkid', genre: 'Électro / Indie FR' },
  { name: 'Phoenix', genre: 'Indie pop FR' },
];
