import type { PopularArtist } from './types';

export const HIP_HOP_ARTISTS: PopularArtist[] = [
  { name: 'Kendrick Lamar', genre: 'Hip-hop' },
  { name: 'Drake', genre: 'Hip-hop' },
  { name: 'Tyler, The Creator', genre: 'Hip-hop' },
  { name: 'Travis Scott', genre: 'Hip-hop' },
  { name: 'Kanye West', genre: 'Hip-hop' },
  { name: 'Eminem', genre: 'Hip-hop' },
  { name: 'Jay-Z', genre: 'Hip-hop' },
  { name: 'Nas', genre: 'Hip-hop' },
  { name: 'J. Cole', genre: 'Hip-hop' },
  { name: 'Lil Wayne', genre: 'Hip-hop' },
  { name: '21 Savage', genre: 'Hip-hop' },
  { name: 'Playboi Carti', genre: 'Hip-hop' },
  { name: 'Future', genre: 'Hip-hop' },
  { name: 'Metro Boomin', genre: 'Hip-hop' },
  { name: 'Post Malone', genre: 'Hip-hop' },
  { name: 'Juice WRLD', genre: 'Hip-hop' },
  { name: 'Lil Uzi Vert', genre: 'Hip-hop' },
  { name: 'Migos', genre: 'Hip-hop' },
  { name: 'Cardi B', genre: 'Hip-hop' },
  { name: 'Nicki Minaj', genre: 'Hip-hop' },
  { name: 'Megan Thee Stallion', genre: 'Hip-hop' },
  { name: 'Doja Cat', genre: 'Hip-hop' },
  { name: 'Ice Spice', genre: 'Hip-hop' },
  { name: 'Central Cee', genre: 'Hip-hop UK' },
  { name: 'Dave', genre: 'Hip-hop UK' },
  { name: 'Stormzy', genre: 'Hip-hop UK' },
  { name: 'Skepta', genre: 'Grime' },
  { name: 'Giggs', genre: 'Hip-hop UK' },
  { name: 'Pop Smoke', genre: 'Hip-hop' },
  { name: 'Lil Baby', genre: 'Hip-hop' },
  { name: 'Gunna', genre: 'Hip-hop' },
  { name: 'Young Thug', genre: 'Hip-hop' },
  { name: 'Lil Durk', genre: 'Hip-hop' },
  { name: 'JID', genre: 'Hip-hop' },
  { name: 'Vince Staples', genre: 'Hip-hop' },
  { name: 'Earl Sweatshirt', genre: 'Hip-hop' },
  { name: 'A$AP Rocky', genre: 'Hip-hop' },
  { name: 'Pusha T', genre: 'Hip-hop' },
  { name: 'ScHoolboy Q', genre: 'Hip-hop' },
  { name: 'Snoop Dogg', genre: 'Hip-hop' },
  { name: 'Dr. Dre', genre: 'Hip-hop' },
  { name: '50 Cent', genre: 'Hip-hop' },
  { name: 'Wu-Tang Clan', genre: 'Hip-hop' },
  { name: 'OutKast', genre: 'Hip-hop' },
  { name: 'André 3000', genre: 'Hip-hop' },
  { name: 'Missy Elliott', genre: 'Hip-hop' },
  { name: 'Lauryn Hill', genre: 'Hip-hop' },
  { name: "Lil' Kim", genre: 'Hip-hop' },
  { name: 'MF DOOM', genre: 'Hip-hop' },
  { name: 'Run The Jewels', genre: 'Hip-hop' },
  { name: 'Denzel Curry', genre: 'Hip-hop' },
  { name: 'JPEGMafia', genre: 'Hip-hop' },
  { name: 'Brockhampton', genre: 'Hip-hop' },
  { name: 'Logic', genre: 'Hip-hop' },
  { name: 'Mac Miller', genre: 'Hip-hop' },
  { name: 'Chance the Rapper', genre: 'Hip-hop' },
  { name: 'Childish Gambino', genre: 'Hip-hop' },
  { name: 'Anderson .Paak', genre: 'Hip-hop' },
  { name: 'Schoolboy Q', genre: 'Hip-hop' },
  { name: '2Pac', genre: 'Hip-hop' },
  { name: 'The Notorious B.I.G.', genre: 'Hip-hop' },
  { name: 'Ice Cube', genre: 'Hip-hop' },
  { name: 'Public Enemy', genre: 'Hip-hop' },
  { name: 'Beastie Boys', genre: 'Hip-hop' },
  { name: 'Run-DMC', genre: 'Hip-hop' },
  { name: 'A Tribe Called Quest', genre: 'Hip-hop' },
  { name: 'De La Soul', genre: 'Hip-hop' },
  { name: 'The Roots', genre: 'Hip-hop' },
  { name: 'Common', genre: 'Hip-hop' },
  { name: 'Mos Def', genre: 'Hip-hop' },
  { name: 'Talib Kweli', genre: 'Hip-hop' },
  { name: 'KRS-One', genre: 'Hip-hop' },
  { name: 'Rakim', genre: 'Hip-hop' },
  { name: 'Slick Rick', genre: 'Hip-hop' },
  { name: 'LL Cool J', genre: 'Hip-hop' },
  { name: 'Queen Latifah', genre: 'Hip-hop' },
  { name: 'Fugees', genre: 'Hip-hop' },
  { name: 'Wyclef Jean', genre: 'Hip-hop' },
  { name: 'Busta Rhymes', genre: 'Hip-hop' },
  { name: 'DMX', genre: 'Hip-hop' },
  { name: 'Method Man', genre: 'Hip-hop' },
  { name: 'Redman', genre: 'Hip-hop' },
  { name: 'Ghostface Killah', genre: 'Hip-hop' },
  { name: 'Raekwon', genre: 'Hip-hop' },
  { name: 'GZA', genre: 'Hip-hop' },
  { name: 'Ol\' Dirty Bastard', genre: 'Hip-hop' },
  { name: 'RZA', genre: 'Hip-hop' },
  { name: 'Killer Mike', genre: 'Hip-hop' },
  { name: 'El-P', genre: 'Hip-hop' },
  { name: 'Aesop Rock', genre: 'Hip-hop' },
  { name: 'Atmosphere', genre: 'Hip-hop' },
  { name: 'Immortal Technique', genre: 'Hip-hop' },
  { name: 'Tech N9ne', genre: 'Hip-hop' },
  { name: 'Eminem & Dr. Dre', genre: 'Hip-hop' },
  { name: 'Travis Barker', genre: 'Hip-hop' },
  { name: 'Kid Cudi', genre: 'Hip-hop' },
  { name: 'Wiz Khalifa', genre: 'Hip-hop' },
  { name: 'Saweetie', genre: 'Hip-hop' },
  { name: 'Latto', genre: 'Hip-hop' },
  { name: 'GloRilla', genre: 'Hip-hop' },
  { name: 'Sexyy Red', genre: 'Hip-hop' },
  { name: '21 Savage & Metro Boomin', genre: 'Hip-hop' },
];
