import type { PopularArtist } from './types';

export const POP_ARTISTS: PopularArtist[] = [
  { name: 'Taylor Swift', genre: 'Pop' },
  { name: 'Billie Eilish', genre: 'Pop' },
  { name: 'Dua Lipa', genre: 'Pop' },
  { name: 'Beyoncé', genre: 'Pop / R&B' },
  { name: 'Rihanna', genre: 'Pop / R&B' },
  { name: 'Lady Gaga', genre: 'Pop' },
  { name: 'Ariana Grande', genre: 'Pop' },
  { name: 'Katy Perry', genre: 'Pop' },
  { name: 'Bruno Mars', genre: 'Pop' },
  { name: 'Ed Sheeran', genre: 'Pop' },
  { name: 'Harry Styles', genre: 'Pop' },
  { name: 'Olivia Rodrigo', genre: 'Pop' },
  { name: 'Sabrina Carpenter', genre: 'Pop' },
  { name: 'Chappell Roan', genre: 'Pop' },
  { name: 'Charli XCX', genre: 'Pop' },
  { name: 'Sia', genre: 'Pop' },
  { name: 'Kesha', genre: 'Pop' },
  { name: 'Shakira', genre: 'Pop' },
  { name: 'Madonna', genre: 'Pop' },
  { name: 'Michael Jackson', genre: 'Pop' },
  { name: 'Whitney Houston', genre: 'Pop' },
  { name: 'Mariah Carey', genre: 'Pop' },
  { name: 'Celine Dion', genre: 'Pop' },
  { name: 'ABBA', genre: 'Pop' },
  { name: 'Spice Girls', genre: 'Pop' },
  { name: 'Backstreet Boys', genre: 'Pop' },
  { name: 'NSYNC', genre: 'Pop' },
  { name: 'One Direction', genre: 'Pop' },
  { name: 'BTS', genre: 'K-pop' },
  { name: 'BLACKPINK', genre: 'K-pop' },
  { name: 'TWICE', genre: 'K-pop' },
  { name: 'NewJeans', genre: 'K-pop' },
  { name: 'Stray Kids', genre: 'K-pop' },
  { name: 'Jungkook', genre: 'K-pop' },
  { name: 'Lisa', genre: 'K-pop' },
  { name: 'The Beatles', genre: 'Pop rock' },
  { name: 'Elvis Presley', genre: 'Pop' },
  { name: 'Adele', genre: 'Soul / Pop' },
  { name: 'Lana Del Rey', genre: 'Pop' },
  { name: 'Lorde', genre: 'Pop' },
  { name: 'Halsey', genre: 'Pop' },
  { name: 'Camila Cabello', genre: 'Pop' },
  { name: 'Shawn Mendes', genre: 'Pop' },
  { name: 'Justin Bieber', genre: 'Pop' },
  { name: 'Selena Gomez', genre: 'Pop' },
  { name: 'Miley Cyrus', genre: 'Pop' },
  { name: 'Demi Lovato', genre: 'Pop' },
  { name: 'Kelly Clarkson', genre: 'Pop' },
  { name: 'P!nk', genre: 'Pop' },
  { name: 'Christina Aguilera', genre: 'Pop' },
  { name: 'Britney Spears', genre: 'Pop' },
  { name: 'Janet Jackson', genre: 'Pop' },
  { name: 'George Michael', genre: 'Pop' },
  { name: 'Wham!', genre: 'Pop' },
  { name: 'Rick Astley', genre: 'Pop' },
  { name: 'Robyn', genre: 'Pop' },
  { name: 'Carly Rae Jepsen', genre: 'Pop' },
  { name: 'Troye Sivan', genre: 'Pop' },
  { name: 'Tate McRae', genre: 'Pop' },
  { name: 'Gracie Abrams', genre: 'Pop' },
  { name: 'Mitski', genre: 'Indie pop' },
  { name: 'Phoebe Bridgers', genre: 'Indie pop' },
  { name: 'Clairo', genre: 'Indie pop' },
  { name: 'Beabadoobee', genre: 'Indie pop' },
  { name: 'FKA twigs', genre: 'Pop' },
  { name: 'Rosalía', genre: 'Flamenco / Pop' },
  { name: 'Måneskin', genre: 'Rock / Pop' },
  { name: 'Imagine Dragons', genre: 'Pop rock' },
  { name: 'Twenty One Pilots', genre: 'Pop rock' },
  { name: 'Coldplay', genre: 'Pop rock' },
  { name: 'Maroon 5', genre: 'Pop rock' },
  { name: 'OneRepublic', genre: 'Pop rock' },
  { name: 'The Script', genre: 'Pop rock' },
  { name: 'Train', genre: 'Pop rock' },
  { name: 'Jason Mraz', genre: 'Pop' },
  { name: 'John Mayer', genre: 'Pop rock' },
  { name: 'James Blunt', genre: 'Pop' },
  { name: 'Sam Smith', genre: 'Pop' },
  { name: 'Lewis Capaldi', genre: 'Pop' },
  { name: 'James Arthur', genre: 'Pop' },
  { name: 'Rag\'n\'Bone Man', genre: 'Pop' },
  { name: 'George Ezra', genre: 'Pop' },
  { name: 'Passenger', genre: 'Pop' },
  { name: 'Vance Joy', genre: 'Pop' },
  { name: 'Of Monsters and Men', genre: 'Indie pop' },
  { name: 'MGMT', genre: 'Indie pop' },
  { name: 'Foster the People', genre: 'Indie pop' },
  { name: 'Walk the Moon', genre: 'Indie pop' },
  { name: 'Bleachers', genre: 'Indie pop' },
  { name: 'Lizzo', genre: 'Pop' },
  { name: 'Doja Cat', genre: 'Pop' },
];
