import type { PopularArtist } from './types';

export const RNB_SOUL_ARTISTS: PopularArtist[] = [
  { name: 'The Weeknd', genre: 'R&B / Pop' },
  { name: 'Frank Ocean', genre: 'R&B' },
  { name: 'SZA', genre: 'R&B' },
  { name: 'D\'Angelo', genre: 'Soul' },
  { name: 'Prince', genre: 'Funk / Pop' },
  { name: 'Parliament-Funkadelic', genre: 'Funk' },
  { name: 'James Brown', genre: 'Funk' },
  { name: 'Stevie Wonder', genre: 'Soul' },
  { name: 'Amy Winehouse', genre: 'Soul' },
  { name: 'Nina Simone', genre: 'Jazz / Soul' },
  { name: 'Usher', genre: 'R&B' },
  { name: 'Chris Brown', genre: 'R&B' },
  { name: 'Pharrell Williams', genre: 'R&B / Pop' },
  { name: 'Alicia Keys', genre: 'R&B' },
  { name: 'John Legend', genre: 'R&B' },
  { name: 'H.E.R.', genre: 'R&B' },
  { name: 'Summer Walker', genre: 'R&B' },
  { name: 'Brent Faiyaz', genre: 'R&B' },
  { name: 'Daniel Caesar', genre: 'R&B' },
  { name: 'Giveon', genre: 'R&B' },
  { name: 'Miguel', genre: 'R&B' },
  { name: 'Khalid', genre: 'R&B' },
  { name: 'Thundercat', genre: 'R&B / Funk' },
  { name: 'Leon Bridges', genre: 'Soul' },
  { name: 'Solange', genre: 'R&B' },
  { name: 'Maxwell', genre: 'R&B' },
  { name: 'Erykah Badu', genre: 'Soul' },
  { name: 'Jill Scott', genre: 'Soul' },
  { name: 'Mary J. Blige', genre: 'R&B' },
  { name: 'Luther Vandross', genre: 'R&B' },
  { name: 'Marvin Gaye', genre: 'Soul' },
  { name: 'Al Green', genre: 'Soul' },
  { name: 'Curtis Mayfield', genre: 'Soul' },
  { name: 'Isaac Hayes', genre: 'Soul' },
  { name: 'Otis Redding', genre: 'Soul' },
  { name: 'Sam Cooke', genre: 'Soul' },
  { name: 'Aretha Franklin', genre: 'Soul' },
  { name: 'Ray Charles', genre: 'Soul' },
  { name: 'Bill Withers', genre: 'Soul' },
  { name: 'Earth, Wind & Fire', genre: 'Funk / Soul' },
  { name: 'Kool & The Gang', genre: 'Funk' },
  { name: 'Chic', genre: 'Disco / Funk' },
  { name: 'Donna Summer', genre: 'Disco' },
  { name: 'Bee Gees', genre: 'Disco / Pop' },
  { name: 'Daft Punk', genre: 'Électro' },
  { name: 'Jamiroquai', genre: 'Funk / Acid jazz' },
  { name: 'Sade', genre: 'Soul' },
  { name: 'D\'Angelo', genre: 'Neo-soul' },
  { name: 'Maxwell', genre: 'Neo-soul' },
  { name: 'Dwele', genre: 'Neo-soul' },
  { name: 'Musiq Soulchild', genre: 'Neo-soul' },
  { name: 'Anthony Hamilton', genre: 'R&B' },
  { name: 'Tyrese', genre: 'R&B' },
  { name: 'Ne-Yo', genre: 'R&B' },
  { name: 'T-Pain', genre: 'R&B' },
  { name: 'The-Dream', genre: 'R&B' },
  { name: 'Miguel', genre: 'R&B' },
  { name: 'PARTYNEXTDOOR', genre: 'R&B' },
  { name: '6LACK', genre: 'R&B' },
  { name: 'Kehlani', genre: 'R&B' },
  { name: 'Jhené Aiko', genre: 'R&B' },
  { name: 'Ella Mai', genre: 'R&B' },
  { name: 'Normani', genre: 'R&B' },
  { name: 'Ciara', genre: 'R&B' },
  { name: 'Aaliyah', genre: 'R&B' },
  { name: 'TLC', genre: 'R&B' },
  { name: 'Destiny\'s Child', genre: 'R&B' },
  { name: 'En Vogue', genre: 'R&B' },
  { name: 'Boyz II Men', genre: 'R&B' },
  { name: 'New Edition', genre: 'R&B' },
  { name: 'Jodeci', genre: 'R&B' },
  { name: 'SWV', genre: 'R&B' },
  { name: 'Brandy', genre: 'R&B' },
  { name: 'Monica', genre: 'R&B' },
  { name: 'Ashanti', genre: 'R&B' },
  { name: 'Keyshia Cole', genre: 'R&B' },
  { name: 'Fantasia', genre: 'R&B' },
  { name: 'Miguel Bosé', genre: 'Pop' },
];
