import type { PopularArtist } from './types';

export const WORLD_LATIN_ARTISTS: PopularArtist[] = [
  { name: 'Bob Marley', genre: 'Reggae' },
  { name: 'Burna Boy', genre: 'Afrobeats' },
  { name: 'Wizkid', genre: 'Afrobeats' },
  { name: 'Bad Bunny', genre: 'Reggaeton' },
  { name: 'J Balvin', genre: 'Reggaeton' },
  { name: 'Rosalía', genre: 'Flamenco / Pop' },
  { name: 'Fela Kuti', genre: 'Afrobeat' },
  { name: 'Angélique Kidjo', genre: 'World' },
  { name: 'Manu Dibango', genre: 'World' },
  { name: 'Amadou & Mariam', genre: 'World' },
  { name: 'Tinariwen', genre: 'World' },
  { name: 'Cesária Évora', genre: 'World' },
  { name: 'Buena Vista Social Club', genre: 'Cubain' },
  { name: 'Caetano Veloso', genre: 'MPB' },
  { name: 'Gilberto Gil', genre: 'MPB' },
  { name: 'Jorge Ben', genre: 'MPB' },
  { name: 'Seu Jorge', genre: 'MPB' },
  { name: 'Anitta', genre: 'Pop BR' },
  { name: 'Karol G', genre: 'Reggaeton' },
  { name: 'Shakira', genre: 'Pop latino' },
  { name: 'Daddy Yankee', genre: 'Reggaeton' },
  { name: 'Ozuna', genre: 'Reggaeton' },
  { name: 'Maluma', genre: 'Reggaeton' },
  { name: 'Farruko', genre: 'Reggaeton' },
  { name: 'C. Tangana', genre: 'Pop espagnol' },
  { name: 'Quevedo', genre: 'Reggaeton' },
  { name: 'Feid', genre: 'Reggaeton' },
  { name: 'Peso Pluma', genre: 'Corridos' },
  { name: 'Junior H', genre: 'Corridos' },
  { name: 'Natanael Cano', genre: 'Corridos' },
  { name: 'Bizarrap', genre: 'Trap latino' },
  { name: 'Trueno', genre: 'Rap latino' },
  { name: 'Duki', genre: 'Trap latino' },
  { name: 'Nicki Nicole', genre: 'Trap latino' },
  { name: 'Maria Becerra', genre: 'Pop latino' },
  { name: 'Tini', genre: 'Pop latino' },
  { name: 'Camilo', genre: 'Pop latino' },
  { name: 'Manuel Turizo', genre: 'Reggaeton' },
  { name: 'Myke Towers', genre: 'Reggaeton' },
  { name: 'Rauw Alejandro', genre: 'Reggaeton' },
  { name: 'Don Omar', genre: 'Reggae' },
  { name: 'Wisin & Yandel', genre: 'Reggaeton' },
  { name: 'Arcángel', genre: 'Reggaeton' },
  { name: 'De La Ghetto', genre: 'Reggaeton' },
  { name: 'Zion & Lennox', genre: 'Reggaeton' },
  { name: 'Nicky Jam', genre: 'Reggaeton' },
  { name: 'Prince Royce', genre: 'Bachata' },
  { name: 'Romeo Santos', genre: 'Bachata' },
  { name: 'Aventura', genre: 'Bachata' },
  { name: 'Marc Anthony', genre: 'Salsa' },
  { name: 'Celia Cruz', genre: 'Salsa' },
  { name: 'Héctor Lavoe', genre: 'Salsa' },
  { name: 'Willie Colón', genre: 'Salsa' },
  { name: 'Rubén Blades', genre: 'Salsa' },
  { name: 'Gloria Estefan', genre: 'Pop latino' },
  { name: 'Selena', genre: 'Tejano' },
  { name: 'Los Tigres del Norte', genre: 'Norteño' },
  { name: 'Vicente Fernández', genre: 'Mariachi' },
  { name: 'Juanes', genre: 'Rock latino' },
  { name: 'Maná', genre: 'Rock latino' },
  { name: 'Café Tacvba', genre: 'Rock latino' },
  { name: 'Molotov', genre: 'Rock latino' },
  { name: 'Ziggy Marley', genre: 'Reggae' },
  { name: 'Damian Marley', genre: 'Reggae' },
  { name: 'Sean Paul', genre: 'Dancehall' },
  { name: 'Shaggy', genre: 'Dancehall' },
  { name: 'Beenie Man', genre: 'Dancehall' },
  { name: 'Vybz Kartel', genre: 'Dancehall' },
  { name: 'Popcaan', genre: 'Dancehall' },
  { name: 'Koffee', genre: 'Reggae' },
  { name: 'Chronixx', genre: 'Reggae' },
  { name: 'Protoje', genre: 'Reggae' },
  { name: 'Rema', genre: 'Afrobeats' },
  { name: 'Tems', genre: 'Afrobeats' },
  { name: 'Asake', genre: 'Afrobeats' },
  { name: 'Ayra Starr', genre: 'Afrobeats' },
  { name: 'Davido', genre: 'Afrobeats' },
  { name: 'Wizkid', genre: 'Afrobeats' },
  { name: 'Burna Boy', genre: 'Afrobeats' },
  { name: 'Fela Kuti', genre: 'Afrobeat' },
  { name: 'Youssou N\'Dour', genre: 'World' },
  { name: 'Salif Keïta', genre: 'World' },
  { name: 'Oumou Sangaré', genre: 'World' },
  { name: 'Alpha Blondy', genre: 'Reggae' },
  { name: 'Lucky Dube', genre: 'Reggae' },
  { name: 'Peter Tosh', genre: 'Reggae' },
  { name: 'Lee Scratch Perry', genre: 'Reggae' },
  { name: 'King Tubby', genre: 'Dub' },
  { name: 'Massive Attack', genre: 'Trip-hop' },
  { name: 'M.I.A.', genre: 'World / Électro' },
  { name: 'Thievery Corporation', genre: 'Downtempo' },
  { name: 'Khruangbin', genre: 'World / Funk' },
  { name: 'Tinariwen', genre: 'Desert blues' },
  { name: 'Bombino', genre: 'Desert blues' },
  { name: 'Ali Farka Touré', genre: 'Blues africain' },
  { name: 'Youssoupha', genre: 'Rap FR' },
];
