/** Connaissance stratégique statique Soundy (docs canoniques — juin 2026). */
export function getCeoStrategicKnowledge() {
  return {
    vision:
      'Réseau social musique live + écoute partagée — unifier découverte, salons sync, lives, carte IRL, reels.',
    productionUrl: 'https://getsoundy.com',
    tabs: ['Actualités', 'Carte', 'Direct', 'Messages', 'Reels'],
    businessModelPriority: [
      'Sponsors natifs (45–55 % revenu cible M24)',
      'Commissions créateurs tips/abos (25–35 %)',
      'Soundy+ abonnement plateforme (10–15 %)',
      'B2B lieux Soundy Pro (5–15 %)',
    ],
    sponsorPackagesEurMonth: {
      map_banner: '800–2 000',
      feed_stories_pack: '1 500–4 000',
      reels_sponsored: '2 000–8 000',
      city_takeover: '5 000–15 000',
    },
    creatorMonetization: {
      liveTipsPlatformFeePercent: 30,
      supporterSubscriptionEur: '4,99–9,99/mois',
      soundyPlusTargetEur: '2,99–4,99/mois',
    },
    infraFixedEurMonth: '41–45 (VPS + PG + domaine + Gmail Pro)',
    infraVariable: 'Cloudflare Stream (minutes livrées + stockage), LiveKit Ship ~50$/mois si dépassement',
    scalePhases: [
      'Phase 0 (fait/en cours): Redis, PM2 cluster, S3 uploads',
      'Phase 1: PostGIS nearby, cache Redis distribué, Sentry',
      'Phase 2: BullMQ, Meilisearch, queues modération',
      'Phase 3: Docker/K8s si >50k CCU',
    ],
    gtmPhases: {
      m0_m3: '30–50 créateurs pilotes, 2 sponsors fondateurs, 1 ville dense',
      m4_m12: 'Paris + Lyon/Marseille, 5 lieux/ville, 5–8 contrats sponsors récurrents',
      m13_m24: 'Soundy Pro Lieu, sales marques, diaspora FR',
    },
    m12TargetsHypothesis: {
      mau: 15000,
      dauMauRatio: 0.25,
      retentionD30: 0.15,
      activeSalonsPerWeek: 200,
      livesPerWeek: 50,
      sponsorArrEur: 40000,
      monetizedCreators: 30,
    },
    criticalRisksFromAudits: [
      'JWT localStorage (XSS) — CRIT-01 httpOnly cookies',
      'IAP Apple/Google obligatoire mobile — Stripe in-app = rejet stores',
      'Sign in with Apple si Google OAuth',
      'LCEN mentions incomplètes (adresse éditeur, DPO)',
      'Nearby O(n) RAM — PostGIS priorité scale',
    ],
    competitiveEdge: [
      'Vertical musique + salons sync + carte + lives + reels dans une PWA',
      'Sponsors natifs 4 emplacements déjà en prod',
      'Géolocalisation debounce + ghost mode',
    ],
    northStarCandidates: [
      'Salons actifs / semaine',
      'Lives >10 min / semaine',
      'DAU/MAU',
      'Contrats sponsors ARR',
      'Créateurs avec Stripe Connect actif',
    ],
    docsIndex: [
      'docs/Soundy-Pitch-Deck.md',
      'docs/PLAN-SPONSORING-PAYANT.md',
      'docs/COUT-APPLICATION.md',
      'docs/STACK-CIBLE.md',
      'docs/INFRA-SOUNDY.md',
      'docs/audit-pre-prod-2026.md',
      'TODO-MANUAL.md',
    ],
    aiTeam: {
      philosophy:
        'Comme Tang Yu (NetDragon), le CEO IA dirige une équipe virtuelle d’agents IA spécialisés. Il peut **proposer** d’en recruter de nouveaux quand un domaine critique manque de bandwidth — jamais sans validation fondateur.',
      recruitmentPrinciples: [
        'Toujours expliquer POURQUOI (preuves [FACT] + coût de l’attente + limites du CEO seul).',
        'Max 1–2 nouveaux agents / mois pour un fondateur solo (coût API + charge cognitive).',
        'Ne pas dupliquer CEO IA ni Dev Agent — compléter leurs angles morts.',
        'Prioriser revenus (Sales) et conformité (Legal) avant CMO/CFO si ressources limitées.',
        'Chaque proposition = dossier complet (voir aiTeamRecommendations dans contexte live).',
      ],
      currentRosterNote: 'Voir aiTeamRoster + aiTeamRecommendations (scores, raisons) dans le contexte live.',
      candidateAgents: [
        {
          id: 'sales',
          name: 'Sales / Sponsors IA',
          emoji: '🤝',
          trigger: '0 sponsor signé · objectif fondateur ≥ 2 · pipeline vide · revenus MRR = 0',
          mission: 'Prospection marques/lieux, scripts outreach, grilles PLAN-SPONSORING, objections, pipeline B2B',
          complements: 'CEO stratégie pricing · Dev Agent = features sponsor · pas de contact direct marques',
          typicalOutputs: ['Liste prospects', 'Scripts email/DM', 'Fiches objection', 'Draft propositions commerciales'],
        },
        {
          id: 'community',
          name: 'Community / Creators IA',
          emoji: '🎤',
          trigger: '< 10 créateurs pilotes actifs · north star salons = 0 · densité ville insuffisante',
          mission: 'Onboarding pilotes, rituels hebdo, activation salons/lives, feedback créateurs → backlog',
          complements: 'CEO north star · CMO acquisition · Dev Agent fixes friction produit',
          typicalOutputs: ['Playbook J0–J7', 'Templates DM', 'Rapport friction hebdo', 'KPI salons/semaine'],
        },
        {
          id: 'legal',
          name: 'Legal IA',
          emoji: '⚖️',
          trigger: 'LCEN incomplet · RDV avocat · stores IAP/Apple · dataGaps legal critical',
          mission: 'Checklist conformité, drafts mentions, brief avocat, matrice risques RGPD/IAP',
          complements: 'CEO risque business · Dev Agent implémentation technique · avocat humain valide',
          typicalOutputs: ['Checklist LCEN', 'Gap analysis TODO-MANUAL', 'ODJ RDV avocat', 'Draft paragraphes légaux'],
        },
        {
          id: 'cmo',
          name: 'CMO IA',
          emoji: '📣',
          trigger: 'Acquisition ville pivot · < 500 users · différenciation messaging · reels/carte sous-utilisés',
          mission: 'Campagnes acquisition, hooks reels, calendrier éditorial, positioning vs concurrence',
          complements: 'Community = rétention · Sales = B2B · CEO = vision',
          typicalOutputs: ['Plan 30j acquisition', 'Hooks contenu', 'ICP créateur', 'Calendrier éditorial'],
        },
        {
          id: 'cfo',
          name: 'CFO IA',
          emoji: '📊',
          trigger: 'Modélisation M12/M24 · levée · unit economics lives · runway < 24 mois',
          mission: 'Scénarios financiers, seuils break-even, alertes burn, pricing cohérent marge',
          complements: 'CEO brief macro · Sales = hypothèses revenus sponsor · Dev = coûts infra',
          typicalOutputs: ['3 scénarios M6–M24', 'Unit economics', 'Alertes CF/LiveKit', 'Note runway'],
        },
        {
          id: 'ops',
          name: 'Ops / Infra IA',
          emoji: '🛠️',
          trigger: 'Incidents prod · coûts Cloudflare/LiveKit · Phase 1 stack · deploy/runbooks',
          mission: 'Runbooks incident, monitoring coûts, checklists deploy, priorisation scale',
          complements: 'Dev Agent = code · CEO = arbitrage business · pas de deploy solo',
          typicalOutputs: ['Runbook incident', 'Rapport santé hebdo', 'Checklist deploy', 'Roadmap Phase 1'],
        },
      ],
      howToCreateNewAgent: [
        '1. Proposer au fondateur : id, nom, emoji, mission, déclencheur métrique, coût API estimé',
        '2. Implémentation repo : backend/src/lib/aiAgents/agents.ts + types AiAgentId',
        '3. System prompt dédié dans systemPrompts.ts (ou fichier séparé)',
        '4. Contexte data optionnel (ex. cmoDataContext.ts) · route admin existante /:agentId/chat',
        '5. AdminAgentsTab.tsx — picker auto depuis AI_AGENTS',
        '6. Demander au fondateur : « Validez-vous la création de l’agent X ? » — jamais auto-déployer',
      ],
      costNote: 'Chaque agent = consommation Anthropic additionnelle (~0,02–0,15 €/brief selon tokens)',
    },
  };
}
