/** Artistes populaires Soundy — jazz, hip-hop, électro, indie, soul, funk, etc. */
export interface PopularArtist {
  name: string;
  genre: string;
}

export const POPULAR_ARTISTS: PopularArtist[] = [
  // Hip-hop / Rap
  { name: 'Kendrick Lamar', genre: 'Hip-hop' },
  { name: 'Drake', genre: 'Hip-hop' },
  { name: 'Tyler, The Creator', genre: 'Hip-hop' },
  { name: 'Lomepal', genre: 'Rap FR' },
  { name: 'Orelsan', genre: 'Rap FR' },
  { name: 'Nekfeu', genre: 'Rap FR' },
  { name: 'Damso', genre: 'Rap FR' },
  { name: 'PNL', genre: 'Rap FR' },
  { name: 'Booba', genre: 'Rap FR' },
  { name: 'Ninho', genre: 'Rap FR' },
  { name: 'Travis Scott', genre: 'Hip-hop' },
  { name: 'Kanye West', genre: 'Hip-hop' },
  { name: 'Eminem', genre: 'Hip-hop' },
  { name: 'Jay-Z', genre: 'Hip-hop' },
  { name: 'Nas', genre: 'Hip-hop' },
  // Électro / House / Techno
  { name: 'Daft Punk', genre: 'Électro' },
  { name: 'Disclosure', genre: 'House' },
  { name: 'Justice', genre: 'Électro' },
  { name: 'M83', genre: 'Électro / Indie' },
  { name: 'Skrillex', genre: 'Dubstep' },
  { name: 'Deadmau5', genre: 'Électro' },
  { name: 'Aphex Twin', genre: 'Électro' },
  { name: 'Bonobo', genre: 'Électro / Chill' },
  { name: 'Caribou', genre: 'Électro' },
  { name: 'Moderat', genre: 'Techno' },
  { name: 'Charlotte de Witte', genre: 'Techno' },
  { name: 'Amelie Lens', genre: 'Techno' },
  { name: 'Fred again..', genre: 'House' },
  { name: 'Peggy Gou', genre: 'House' },
  // Jazz
  { name: 'Miles Davis', genre: 'Jazz' },
  { name: 'John Coltrane', genre: 'Jazz' },
  { name: 'Billie Holiday', genre: 'Jazz' },
  { name: 'Nina Simone', genre: 'Jazz / Soul' },
  { name: 'Kamasi Washington', genre: 'Jazz' },
  { name: 'Robert Glasper', genre: 'Jazz' },
  { name: 'Esperanza Spalding', genre: 'Jazz' },
  // Soul / Funk / R&B
  { name: 'D\'Angelo', genre: 'Soul' },
  { name: 'Frank Ocean', genre: 'R&B' },
  { name: 'SZA', genre: 'R&B' },
  { name: 'The Weeknd', genre: 'R&B / Pop' },
  { name: 'Prince', genre: 'Funk / Pop' },
  { name: 'Parliament-Funkadelic', genre: 'Funk' },
  { name: 'James Brown', genre: 'Funk' },
  { name: 'Stevie Wonder', genre: 'Soul' },
  { name: 'Amy Winehouse', genre: 'Soul' },
  { name: 'Adele', genre: 'Soul / Pop' },
  // Indie / Rock / Alternatif
  { name: 'The Killers', genre: 'Indie rock' },
  { name: 'Arctic Monkeys', genre: 'Indie rock' },
  { name: 'Phoenix', genre: 'Indie pop' },
  { name: 'Tame Impala', genre: 'Indie / Psyché' },
  { name: 'Radiohead', genre: 'Alternatif' },
  { name: 'Arcade Fire', genre: 'Indie rock' },
  { name: 'Foals', genre: 'Indie rock' },
  { name: 'Stromae', genre: 'Pop / Électro FR' },
  { name: 'Angèle', genre: 'Pop FR' },
  { name: 'Christine and the Queens', genre: 'Pop / Électro FR' },
  { name: 'Vianney', genre: 'Pop FR' },
  { name: 'Zaz', genre: 'Chanson FR' },
  // Pop / Variété internationale
  { name: 'Taylor Swift', genre: 'Pop' },
  { name: 'Billie Eilish', genre: 'Pop' },
  { name: 'Dua Lipa', genre: 'Pop' },
  { name: 'Beyoncé', genre: 'Pop / R&B' },
  { name: 'Rihanna', genre: 'Pop / R&B' },
  { name: 'Lady Gaga', genre: 'Pop' },
  { name: 'Coldplay', genre: 'Pop rock' },
  { name: 'Fleetwood Mac', genre: 'Rock' },
  { name: 'Pink Floyd', genre: 'Rock' },
  { name: 'Led Zeppelin', genre: 'Rock' },
  // Reggae / Afro / World
  { name: 'Bob Marley', genre: 'Reggae' },
  { name: 'Burna Boy', genre: 'Afrobeats' },
  { name: 'Wizkid', genre: 'Afrobeats' },
  { name: 'Rosalía', genre: 'Flamenco / Pop' },
  { name: 'Bad Bunny', genre: 'Reggaeton' },
  { name: 'J Balvin', genre: 'Reggaeton' },
  // Classiques / Découverte
  { name: 'Rick Astley', genre: 'Pop' },
  { name: 'Queen', genre: 'Rock' },
  { name: 'David Bowie', genre: 'Rock' },
  { name: 'Massive Attack', genre: 'Trip-hop' },
  { name: 'Portishead', genre: 'Trip-hop' },
  { name: 'Gorillaz', genre: 'Alternatif' },
  { name: 'LCD Soundsystem', genre: 'Électro / Rock' },
  { name: 'Jamiroquai', genre: 'Funk / Acid jazz' },
];
