import type { PopularArtist } from './types';

export const ELECTRONIC_ARTISTS: PopularArtist[] = [
  { name: 'Daft Punk', genre: 'Électro' },
  { name: 'Disclosure', genre: 'House' },
  { name: 'Justice', genre: 'Électro' },
  { name: 'M83', genre: 'Électro / Indie' },
  { name: 'Skrillex', genre: 'Dubstep' },
  { name: 'Deadmau5', genre: 'Électro' },
  { name: 'Aphex Twin', genre: 'Électro' },
  { name: 'Bonobo', genre: 'Électro / Chill' },
  { name: 'Caribou', genre: 'Électro' },
  { name: 'Moderat', genre: 'Techno' },
  { name: 'Charlotte de Witte', genre: 'Techno' },
  { name: 'Amelie Lens', genre: 'Techno' },
  { name: 'Fred again..', genre: 'House' },
  { name: 'Peggy Gou', genre: 'House' },
  { name: 'The Chemical Brothers', genre: 'Électro' },
  { name: 'Underworld', genre: 'Électro' },
  { name: 'Orbital', genre: 'Électro' },
  { name: 'Kraftwerk', genre: 'Électro' },
  { name: 'Tiësto', genre: 'Trance' },
  { name: 'Armin van Buuren', genre: 'Trance' },
  { name: 'Calvin Harris', genre: 'House' },
  { name: 'David Guetta', genre: 'House' },
  { name: 'Alesso', genre: 'House' },
  { name: 'Marshmello', genre: 'Électro' },
  { name: 'Kygo', genre: 'House' },
  { name: 'Avicii', genre: 'House' },
  { name: 'Swedish House Mafia', genre: 'House' },
  { name: 'Eric Prydz', genre: 'House' },
  { name: 'Tale of Us', genre: 'Techno' },
  { name: 'Âme', genre: 'Techno' },
  { name: 'Dixon', genre: 'House' },
  { name: 'Solomun', genre: 'House' },
  { name: 'Carl Cox', genre: 'Techno' },
  { name: 'Richie Hawtin', genre: 'Techno' },
  { name: 'Nina Kraviz', genre: 'Techno' },
  { name: 'Four Tet', genre: 'Électro' },
  { name: 'Floating Points', genre: 'Électro' },
  { name: 'Nicolas Jaar', genre: 'Électro' },
  { name: 'Jungle', genre: 'Électro / Funk' },
  { name: 'Parcels', genre: 'Disco / Électro' },
  { name: 'RÜFÜS DU SOL', genre: 'Électro' },
  { name: 'ODESZA', genre: 'Électro' },
  { name: 'Flume', genre: 'Électro' },
  { name: 'Porter Robinson', genre: 'Électro' },
  { name: 'Madeon', genre: 'Électro' },
  { name: 'Zedd', genre: 'Électro' },
  { name: 'Diplo', genre: 'Électro' },
  { name: 'Major Lazer', genre: 'Électro' },
  { name: 'DJ Snake', genre: 'Électro' },
  { name: 'Martin Garrix', genre: 'Électro' },
  { name: 'Hardwell', genre: 'Électro' },
  { name: 'Afrojack', genre: 'Électro' },
  { name: 'Steve Aoki', genre: 'Électro' },
  { name: 'Bassnectar', genre: 'Dubstep' },
  { name: 'Excision', genre: 'Dubstep' },
  { name: 'RL Grime', genre: 'Trap' },
  { name: 'Baauer', genre: 'Trap' },
  { name: 'Rustie', genre: 'Électro' },
  { name: 'Flying Lotus', genre: 'Électro' },
  { name: 'Thundercat', genre: 'Électro / Funk' },
  { name: 'Kaytranada', genre: 'House' },
  { name: 'SG Lewis', genre: 'House' },
  { name: 'Jamie xx', genre: 'House' },
  { name: 'The xx', genre: 'Indie / Électro' },
  { name: 'Hot Chip', genre: 'Électro' },
  { name: 'LCD Soundsystem', genre: 'Électro / Rock' },
  { name: 'Soulwax', genre: 'Électro' },
  { name: '2ManyDJs', genre: 'Électro' },
  { name: 'Gesaffelstein', genre: 'Électro' },
  { name: 'SebastiAn', genre: 'Électro' },
  { name: 'Kavinsky', genre: 'Électro' },
  { name: 'Vitalic', genre: 'Électro' },
  { name: 'Mr. Oizo', genre: 'Électro' },
  { name: 'Boys Noize', genre: 'Électro' },
  { name: 'Modeselektor', genre: 'Électro' },
  { name: 'Paul Kalkbrenner', genre: 'Techno' },
  { name: 'Ben Böhmer', genre: 'Électro' },
  { name: 'Lane 8', genre: 'House' },
  { name: 'Yotto', genre: 'House' },
  { name: 'CamelPhat', genre: 'House' },
  { name: 'Fisher', genre: 'House' },
  { name: 'Chris Lake', genre: 'House' },
  { name: 'John Summit', genre: 'House' },
  { name: 'Dom Dolla', genre: 'House' },
  { name: 'Purple Disco Machine', genre: 'Disco' },
  { name: 'Duke Dumont', genre: 'House' },
  { name: 'Disclosure', genre: 'House' },
  { name: 'Jamie xx', genre: 'House' },
  { name: 'Massive Attack', genre: 'Trip-hop' },
  { name: 'Portishead', genre: 'Trip-hop' },
  { name: 'Burial', genre: 'Dubstep' },
  { name: 'Boards of Canada', genre: 'Électro' },
  { name: 'Tycho', genre: 'Chillwave' },
  { name: 'Washed Out', genre: 'Chillwave' },
  { name: 'Toro y Moi', genre: 'Chillwave' },
  { name: 'Com Truise', genre: 'Synthwave' },
  { name: 'Kavinsky', genre: 'Synthwave' },
];
