import type { PopularArtist } from './types';

export const FR_RAP_ARTISTS: PopularArtist[] = [
  { name: 'SCH', genre: 'Rap FR' },
  { name: 'Lomepal', genre: 'Rap FR' },
  { name: 'Orelsan', genre: 'Rap FR' },
  { name: 'Nekfeu', genre: 'Rap FR' },
  { name: 'Damso', genre: 'Rap FR' },
  { name: 'PNL', genre: 'Rap FR' },
  { name: 'Booba', genre: 'Rap FR' },
  { name: 'Ninho', genre: 'Rap FR' },
  { name: 'Jul', genre: 'Rap FR' },
  { name: 'Gims', genre: 'Rap FR' },
  { name: 'Vald', genre: 'Rap FR' },
  { name: 'Hamza', genre: 'Rap FR' },
  { name: 'Laylow', genre: 'Rap FR' },
  { name: 'Josman', genre: 'Rap FR' },
  { name: 'Freeze Corleone', genre: 'Rap FR' },
  { name: 'Zola', genre: 'Rap FR' },
  { name: 'Kaaris', genre: 'Rap FR' },
  { name: 'Lacrim', genre: 'Rap FR' },
  { name: 'MHD', genre: 'Rap FR' },
  { name: 'Sofiane', genre: 'Rap FR' },
  { name: 'Niska', genre: 'Rap FR' },
  { name: 'Soolking', genre: 'Rap FR' },
  { name: 'Gradur', genre: 'Rap FR' },
  { name: 'Kalash Criminel', genre: 'Rap FR' },
  { name: 'Alonzo', genre: 'Rap FR' },
  { name: 'Naps', genre: 'Rap FR' },
  { name: 'Dinos', genre: 'Rap FR' },
  { name: 'Luidji', genre: 'Rap FR' },
  { name: 'Kekra', genre: 'Rap FR' },
  { name: 'Hornet La Frappe', genre: 'Rap FR' },
  { name: 'Leto', genre: 'Rap FR' },
  { name: 'Tiakola', genre: 'Rap FR' },
  { name: 'Guy2Bezbar', genre: 'Rap FR' },
  { name: 'Chilla', genre: 'Rap FR' },
  { name: "Rim'K", genre: 'Rap FR' },
  { name: 'IAM', genre: 'Rap FR' },
  { name: 'Assassin', genre: 'Rap FR' },
  { name: 'MC Solaar', genre: 'Rap FR' },
  { name: 'Oxmo Pousse-Caillou', genre: 'Rap FR' },
  { name: 'Youssoupha', genre: 'Rap FR' },
  { name: 'Rohff', genre: 'Rap FR' },
  { name: 'La Fouine', genre: 'Rap FR' },
  { name: 'Sniper', genre: 'Rap FR' },
  { name: 'Fonky Family', genre: 'Rap FR' },
  { name: 'Kery James', genre: 'Rap FR' },
  { name: 'Médine', genre: 'Rap FR' },
  { name: 'Abd Al Malik', genre: 'Rap FR' },
  { name: 'Georgio', genre: 'Rap FR' },
  { name: "L'Algérino", genre: 'Rap FR' },
  { name: 'Niro', genre: 'Rap FR' },
  { name: 'Sefyu', genre: 'Rap FR' },
  { name: 'Lefa', genre: 'Rap FR' },
  { name: 'Alpha Wann', genre: 'Rap FR' },
  { name: 'Sneazzy', genre: 'Rap FR' },
  { name: 'Luv Resval', genre: 'Rap FR' },
  { name: 'Bigflo & Oli', genre: 'Rap FR' },
  { name: 'Soprano', genre: 'Rap FR' },
  { name: 'Black M', genre: 'Rap FR' },
  { name: 'Maître Gims', genre: 'Rap FR' },
  { name: 'Gazo', genre: 'Rap FR' },
  { name: 'Franglish', genre: 'Rap FR' },
  { name: 'Dosseh', genre: 'Rap FR' },
  { name: 'Seth Gueko', genre: 'Rap FR' },
  { name: 'Columbine', genre: 'Rap FR' },
  { name: 'Lujipeka', genre: 'Rap FR' },
  { name: 'Caballero & JeanJass', genre: 'Rap FR' },
  { name: 'Disiz', genre: 'Rap FR' },
  { name: 'Scylla', genre: 'Rap FR' },
  { name: 'Hugo TSR', genre: 'Rap FR' },
  { name: 'PLK', genre: 'Rap FR' },
  { name: 'SDM', genre: 'Rap FR' },
  { name: 'Werenoi', genre: 'Rap FR' },
  { name: 'Ziak', genre: 'Rap FR' },
  { name: 'Kerchak', genre: 'Rap FR' },
  { name: 'Favé', genre: 'Rap FR' },
  { name: "Heuss l'Enfoiré", genre: 'Rap FR' },
  { name: 'Niska & Ninho', genre: 'Rap FR' },
  { name: 'Ninho & Niska', genre: 'Rap FR' },
  { name: 'Booba & Kaaris', genre: 'Rap FR' },
  { name: 'Fabe', genre: 'Rap FR' },
  { name: '113', genre: 'Rap FR' },
  { name: 'NTM', genre: 'Rap FR' },
  { name: 'Ministère A.M.E.R.', genre: 'Rap FR' },
  { name: 'Arsenik', genre: 'Rap FR' },
  { name: 'La Cliqua', genre: 'Rap FR' },
  { name: 'Sinik', genre: 'Rap FR' },
  { name: 'Kamini', genre: 'Rap FR' },
  { name: 'Sexion d\'Assaut', genre: 'Rap FR' },
  { name: 'Maska', genre: 'Rap FR' },
  { name: 'Dadju', genre: 'Rap FR' },
  { name: 'Slimane', genre: 'Rap FR' },
];
