import type { PopularArtist } from './types';

export const JAZZ_ARTISTS: PopularArtist[] = [
  { name: 'Miles Davis', genre: 'Jazz' },
  { name: 'John Coltrane', genre: 'Jazz' },
  { name: 'Billie Holiday', genre: 'Jazz' },
  { name: 'Kamasi Washington', genre: 'Jazz' },
  { name: 'Robert Glasper', genre: 'Jazz' },
  { name: 'Esperanza Spalding', genre: 'Jazz' },
  { name: 'Herbie Hancock', genre: 'Jazz' },
  { name: 'Wayne Shorter', genre: 'Jazz' },
  { name: 'Thelonious Monk', genre: 'Jazz' },
  { name: 'Charlie Parker', genre: 'Jazz' },
  { name: 'Duke Ellington', genre: 'Jazz' },
  { name: 'Count Basie', genre: 'Jazz' },
  { name: 'Ella Fitzgerald', genre: 'Jazz' },
  { name: 'Sarah Vaughan', genre: 'Jazz' },
  { name: 'Chet Baker', genre: 'Jazz' },
  { name: 'Keith Jarrett', genre: 'Jazz' },
  { name: 'Brad Mehldau', genre: 'Jazz' },
  { name: 'Pat Metheny', genre: 'Jazz' },
  { name: 'Norah Jones', genre: 'Jazz / Pop' },
  { name: 'Diana Krall', genre: 'Jazz' },
  { name: 'Cécile McLorin Salvant', genre: 'Jazz' },
  { name: 'Snarky Puppy', genre: 'Jazz fusion' },
  { name: 'Weather Report', genre: 'Jazz fusion' },
  { name: 'Mahavishnu Orchestra', genre: 'Jazz fusion' },
  { name: 'Return to Forever', genre: 'Jazz fusion' },
  { name: 'Chick Corea', genre: 'Jazz' },
  { name: 'Dave Brubeck', genre: 'Jazz' },
  { name: 'Oscar Peterson', genre: 'Jazz' },
  { name: 'Art Blakey', genre: 'Jazz' },
  { name: 'Horace Silver', genre: 'Jazz' },
  { name: 'Sonny Rollins', genre: 'Jazz' },
  { name: 'Dexter Gordon', genre: 'Jazz' },
  { name: 'Cannonball Adderley', genre: 'Jazz' },
  { name: 'Lee Morgan', genre: 'Jazz' },
  { name: 'Freddie Hubbard', genre: 'Jazz' },
  { name: 'Miles Davis Quintet', genre: 'Jazz' },
  { name: 'Charles Mingus', genre: 'Jazz' },
  { name: 'Ornette Coleman', genre: 'Jazz' },
  { name: 'Sun Ra', genre: 'Jazz' },
  { name: 'Pharoah Sanders', genre: 'Jazz' },
  { name: 'Alice Coltrane', genre: 'Jazz' },
  { name: 'Brad Mehldau Trio', genre: 'Jazz' },
  { name: 'Hiromi', genre: 'Jazz' },
  { name: 'GoGo Penguin', genre: 'Jazz' },
  { name: 'BadBadNotGood', genre: 'Jazz' },
  { name: 'Thundercat', genre: 'Jazz / Funk' },
  { name: 'Nina Simone', genre: 'Jazz / Soul' },
  { name: 'Louis Armstrong', genre: 'Jazz' },
  { name: 'Dizzy Gillespie', genre: 'Jazz' },
  { name: 'Bud Powell', genre: 'Jazz' },
  { name: 'Bill Evans', genre: 'Jazz' },
  { name: 'McCoy Tyner', genre: 'Jazz' },
  { name: 'Joe Henderson', genre: 'Jazz' },
  { name: 'Stan Getz', genre: 'Jazz' },
  { name: 'Antônio Carlos Jobim', genre: 'Bossa nova' },
  { name: 'João Gilberto', genre: 'Bossa nova' },
  { name: 'Astrud Gilberto', genre: 'Bossa nova' },
  { name: 'Sérgio Mendes', genre: 'Bossa nova' },
  { name: 'Caetano Veloso', genre: 'Bossa nova' },
  { name: 'Gilberto Gil', genre: 'Bossa nova' },
];
