import type { PopularArtist } from './types';

export const ROCK_INDIE_ARTISTS: PopularArtist[] = [
  { name: 'The Killers', genre: 'Indie rock' },
  { name: 'Arctic Monkeys', genre: 'Indie rock' },
  { name: 'Tame Impala', genre: 'Indie / Psyché' },
  { name: 'Radiohead', genre: 'Alternatif' },
  { name: 'Arcade Fire', genre: 'Indie rock' },
  { name: 'Foals', genre: 'Indie rock' },
  { name: 'Coldplay', genre: 'Pop rock' },
  { name: 'Fleetwood Mac', genre: 'Rock' },
  { name: 'Pink Floyd', genre: 'Rock' },
  { name: 'Led Zeppelin', genre: 'Rock' },
  { name: 'Queen', genre: 'Rock' },
  { name: 'David Bowie', genre: 'Rock' },
  { name: 'Gorillaz', genre: 'Alternatif' },
  { name: 'LCD Soundsystem', genre: 'Électro / Rock' },
  { name: 'Foo Fighters', genre: 'Rock' },
  { name: 'Nirvana', genre: 'Grunge' },
  { name: 'Pearl Jam', genre: 'Grunge' },
  { name: 'Red Hot Chili Peppers', genre: 'Rock' },
  { name: 'Muse', genre: 'Rock' },
  { name: 'Oasis', genre: 'Britpop' },
  { name: 'Blur', genre: 'Britpop' },
  { name: 'The Strokes', genre: 'Indie rock' },
  { name: 'Interpol', genre: 'Indie rock' },
  { name: 'The National', genre: 'Indie rock' },
  { name: 'Vampire Weekend', genre: 'Indie rock' },
  { name: 'Bon Iver', genre: 'Indie folk' },
  { name: 'Fleet Foxes', genre: 'Indie folk' },
  { name: 'Wilco', genre: 'Indie rock' },
  { name: 'The Smashing Pumpkins', genre: 'Rock' },
  { name: 'Green Day', genre: 'Punk rock' },
  { name: 'Blink-182', genre: 'Punk rock' },
  { name: 'Linkin Park', genre: 'Rock' },
  { name: 'Metallica', genre: 'Metal' },
  { name: 'Iron Maiden', genre: 'Metal' },
  { name: 'Black Sabbath', genre: 'Metal' },
  { name: 'AC/DC', genre: 'Rock' },
  { name: 'Guns N\' Roses', genre: 'Rock' },
  { name: 'U2', genre: 'Rock' },
  { name: 'The Rolling Stones', genre: 'Rock' },
  { name: 'The Who', genre: 'Rock' },
  { name: 'Jimi Hendrix', genre: 'Rock' },
  { name: 'Bob Dylan', genre: 'Folk rock' },
  { name: 'Neil Young', genre: 'Rock' },
  { name: 'Bruce Springsteen', genre: 'Rock' },
  { name: 'Tom Petty', genre: 'Rock' },
  { name: 'Kings of Leon', genre: 'Rock' },
  { name: 'Fall Out Boy', genre: 'Pop punk' },
  { name: 'Panic! At The Disco', genre: 'Pop rock' },
  { name: 'My Chemical Romance', genre: 'Emo' },
  { name: 'Paramore', genre: 'Rock' },
  { name: 'Florence + The Machine', genre: 'Indie pop' },
  { name: 'The 1975', genre: 'Indie pop' },
  { name: 'Sam Fender', genre: 'Indie rock' },
  { name: 'Wet Leg', genre: 'Indie rock' },
  { name: 'Fontaines D.C.', genre: 'Indie rock' },
  { name: 'The Cure', genre: 'Post-punk' },
  { name: 'Joy Division', genre: 'Post-punk' },
  { name: 'New Order', genre: 'Post-punk' },
  { name: 'Depeche Mode', genre: 'Synth-pop' },
  { name: 'The Smiths', genre: 'Indie rock' },
  { name: 'R.E.M.', genre: 'Rock' },
  { name: 'Pixies', genre: 'Indie rock' },
  { name: 'Sonic Youth', genre: 'Indie rock' },
  { name: 'Pavement', genre: 'Indie rock' },
  { name: 'Beck', genre: 'Alternatif' },
  { name: 'Beastie Boys', genre: 'Hip-hop / Rock' },
  { name: 'Rage Against the Machine', genre: 'Rock' },
  { name: 'System of a Down', genre: 'Metal' },
  { name: 'Tool', genre: 'Metal' },
  { name: 'Deftones', genre: 'Metal' },
  { name: 'Slipknot', genre: 'Metal' },
  { name: 'Rammstein', genre: 'Metal' },
  { name: 'Gojira', genre: 'Metal' },
  { name: 'Architects', genre: 'Metal' },
  { name: 'Bring Me The Horizon', genre: 'Metal' },
  { name: 'M83', genre: 'Électro / Indie' },
  { name: 'Massive Attack', genre: 'Trip-hop' },
  { name: 'Portishead', genre: 'Trip-hop' },
  { name: 'Tricky', genre: 'Trip-hop' },
  { name: 'Björk', genre: 'Alternatif' },
  { name: 'Sigur Rós', genre: 'Post-rock' },
  { name: 'Explosions in the Sky', genre: 'Post-rock' },
  { name: 'Godspeed You! Black Emperor', genre: 'Post-rock' },
  { name: 'Mogwai', genre: 'Post-rock' },
  { name: 'The White Stripes', genre: 'Rock' },
  { name: 'The Black Keys', genre: 'Rock' },
  { name: 'Jack White', genre: 'Rock' },
  { name: 'Queens of the Stone Age', genre: 'Rock' },
  { name: 'Foo Fighters', genre: 'Rock' },
  { name: 'Soundgarden', genre: 'Grunge' },
  { name: 'Alice in Chains', genre: 'Grunge' },
  { name: 'Stone Temple Pilots', genre: 'Grunge' },
  { name: 'Creedence Clearwater Revival', genre: 'Rock' },
  { name: 'The Doors', genre: 'Rock' },
  { name: 'Jimi Hendrix Experience', genre: 'Rock' },
  { name: 'Cream', genre: 'Rock' },
  { name: 'Deep Purple', genre: 'Rock' },
  { name: 'Aerosmith', genre: 'Rock' },
  { name: 'Bon Jovi', genre: 'Rock' },
  { name: 'Def Leppard', genre: 'Rock' },
  { name: 'Van Halen', genre: 'Rock' },
  { name: 'Scorpions', genre: 'Rock' },
  { name: 'Europe', genre: 'Rock' },
  { name: 'Dire Straits', genre: 'Rock' },
  { name: 'Eagles', genre: 'Rock' },
  { name: 'Fleetwood Mac', genre: 'Rock' },
  { name: 'The Beach Boys', genre: 'Rock' },
  { name: 'The Kinks', genre: 'Rock' },
  { name: 'The Velvet Underground', genre: 'Rock' },
  { name: 'Lou Reed', genre: 'Rock' },
  { name: 'Iggy Pop', genre: 'Rock' },
  { name: 'Patti Smith', genre: 'Rock' },
  { name: 'Talking Heads', genre: 'New wave' },
  { name: 'Blondie', genre: 'New wave' },
  { name: 'Kraftwerk', genre: 'Électro' },
];
